---
# tasks file for roles/elk

- name: ELK repo
  copy:
    src: CentOS-ELK.repo
    dest: /etc/yum.repos.d/
  tags: web

- name: Install Filebeat
  package:
    name: filebeat
    state: latest
  tags: web
  
- name: Conf filebeat
  copy:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat
  tags: web
  
- name: Copy nginx.conf from template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  tags: web
